# Generated by Django 4.2.16 on 2024-10-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_currencyvalues_value_in_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalues',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='currencyvalues',
            name='value_in_usd',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
